# Generated by Django 3.2.5 on 2021-07-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_chores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.chores'),
            preserve_default=False,
        ),
    ]
