# Generated by Django 3.2.5 on 2021-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_users_user_chores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chores',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='chores',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
