# Generated by Django 3.2.5 on 2021-07-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_users_user_chores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_chores',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.chores'),
        ),
    ]
