# Generated by Django 3.2.5 on 2021-07-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_users_user_chores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_chores',
        ),
    ]
