# Generated by Django 3.2.5 on 2021-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210724_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chores',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
