# Generated by Django 3.2.5 on 2021-07-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_chores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.chores'),
        ),
    ]
