# Generated by Django 3.2.5 on 2021-07-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_users_user_chores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
