# Generated by Django 3.2.5 on 2021-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chores',
            name='description',
        ),
        migrations.AddField(
            model_name='chores',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chores',
            name='name',
            field=models.CharField(auto_created='+25', max_length=250, null=True),
        ),
    ]
