# Generated by Django 3.2.5 on 2021-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20210730_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='chores',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
