# Generated by Django 3.2.5 on 2021-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_chores_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='name',
            field=models.CharField(default='+25', max_length=250, null=True),
        ),
    ]
