# Generated by Django 3.2.5 on 2021-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_chores_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chores',
            name='complete',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
